blood_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls'))
]

info/urls.py
from django.urls import path
from .views import index, blood_entry

app_name = 'info'

urlpatterns = [
    path('', index, name='home'),
    path('blood-entry/', blood_entry, name='blood-entry'),

]

info/models.py
from django.contrib.auth.models import User
from django.db import models


class BloodInfo(models.Model):
    Male = 'Male'
    Female = 'Female'
    SEX_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
    ]
    A_POSITIVE = 'A+'
    A_NEGATIVE = 'A-'
    B_POSITIVE = 'B+'
    B_NEGATIVE = 'B-'
    AB_POSITIVE = 'AB+'
    AB_NEGATIVE = 'AB-'
    O_POSITIVE = 'O+'
    O_NEGATIVE = 'O-'

    BLOOD_GROUP_CHOICES = [
        (A_POSITIVE,'A+'),
        (A_NEGATIVE, 'A-'),
        (B_POSITIVE, 'B+'),
        (B_NEGATIVE, 'B-'),
        (AB_POSITIVE, 'AB+'),
        (AB_NEGATIVE, 'AB-'),
        (O_POSITIVE, 'O+'),
        (O_NEGATIVE, 'O-'),
    ]
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    age = models.IntegerField(blank=False, default=1)
    blood_group = models.CharField(max_length=10,
                                   choices=BLOOD_GROUP_CHOICES,
                                   default='')
    sex = models.CharField(
        max_length=10,
        choices=SEX_CHOICES,
        default=Male,
    )
    location = models.CharField(max_length=150, blank=False)

    def __str__(self):
        return self.first_name + ' ' + self.blood_group

info/forms.py
from django import forms
from .models import BloodInfo


class BloodInfoForm(forms.ModelForm):

    class Meta:
        model = BloodInfo
        exclude = []

info/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth import authenticate
from .forms import BloodInfoForm
from .models import BloodInfo


def index(request):
    all_blood_info = BloodInfo.objects.all()
    if request.method == 'POST':
        query = request.POST.get('query')
        if query == 'Male':
            query = 'M'
        elif query == 'Female':
            query = 'F'

        all_blood_info = all_blood_info.filter(
            Q(blood_group__icontains=query) |
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(location__icontains=query) |
            Q(age__iexact=query) |
            Q(sex__icontains=query)
        ).distinct()
    context = {
        'all_blood_info': all_blood_info
    }
    return render(request, 'info/all_blood_records.html', context=context)


def blood_entry(request):
    if request.method == "POST":
        donor_form = BloodInfoForm(data=request.POST)
        # print(request.POST)
        if donor_form.is_valid():
            first_name = donor_form.cleaned_data['first_name']
            last_name = donor_form.cleaned_data['last_name']
            sex = donor_form.cleaned_data['sex']
            age = donor_form.cleaned_data['age']
            location = donor_form.cleaned_data['location']
            donor_form.save()

            return redirect('info:blood-entry')

        else:
            print(donor_form.errors)
            return redirect('info:blood-entry')
        print("POSTING")
    else:
        form = BloodInfoForm
        context = {
            'form': form
        }
        print("GETTING")
        return render(request, "info/add_donor.html", context=context)

info/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<!--    Bootstrap 4 CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body>

    {% include 'info/nav-bar.html' %}

    {% block body %}

    <!-- here come index.html -->

    {% endblock %}

<!--    Bootstrap 4 JS-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">
    </script>

</body>
</html>

info/templates/info/add_donor.html
{% extends 'base.html' %}


{% block body %}


    <div class="add-donor container">
        <br>
        <h2 class="text-center">Please Register Here</h2>
        <br>
        <form method="POST" action="{% url 'info:blood-entry' %}">
            {% csrf_token %}
            {{ form.as_p }}
            {% if form.errors %}
                <ol>
                {% for error in form.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}

            <input type="submit" class="btn btn-primary" value="Insert">
        </form>

        {% if has_profile %}
        <p>You Successfully Signed In!</p>
        {% endif %}
    </div>

{% endblock %}

info/templates/info/all_blood_records.html
{% extends 'base.html' %}


{% block body %}

    <div class="container-fluid">
        <br>
        <h4 class="text-center">Information of Blood Donors</h4>
        <br>
        <div class="all-records text-center">
            {% if all_blood_info %}
            <ul>
                {% for blood_info in all_blood_info %}

                    <p>Blood Group: <strong>{{ blood_info.blood_group }}</strong></p>
                    <h4>Donor Information</h4>
                    <p>Name: <strong>{{ blood_info.first_name }} {{ blood_info.last_name }}</strong></p>
                    <p><strong>Sex: {{ blood_info.sex }} </strong></p>
                    <p><strong>Age: {{ blood_info.age }}</strong></p>
                    <p>Location: {{ blood_info.location }}</p>
                <hr>

                {% endfor %}
            </ul>
            {% else %}
                <span  class="text-danger">No Blood Information Available!</span>
            {% endif %}
        </div>
    </div>

{% endblock %}

info/templates/info/nav-bar.html
    <div>
        <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'info:home' %}">BloodBank</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <div class="offset-md-7 collapse navbar-collapse justify-content-md-center text-center" id="navbarSupportedContent">

              <a class="navbar-brand" href="{% url 'info:blood-entry' %}">Entry Record</a>

            <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'info:home' %}">
                {% csrf_token %}
              <input class="form-control mr-sm-2" type="search"
                     placeholder="Search"
                     name="query"
                     aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
    </header>

    </div>